config/routes.rb
Rails.application.routes.draw do
  resources :services

  get 'pages/index'

  get 'pages/prices', as: :prices

  get 'pages/contacts', as: :contacts

  get 'pages/services'

  get 'pages/order', as: :order

  root 'pages#index'

end

app/models/service.rb
class Service < ActiveRecord::Base

  def span_this_please
    first_word = self.description.split[0]
    return self.description.sub(/(?<foo>#{first_word})/, '<span>\k<foo></span>')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @services = Service.first(4).reverse
  end

  def prices
  end

  def contacts
  end

  def services
  end

  def order
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.paginate(:page => params[:page], :per_page => 3)
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:title, :description, :price, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bux</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper">

  <header class="header">
    <div class="upbox">
      <div class="logo">
        <%= link_to root_url do %>
            <h1>Гроссбух</h1>
        <% end %>
      </div>
      <div class="menu">
        <ul class="main">
          <li class="col"><%= link_to 'Главная', root_path %></li>
          <li class="col"><%= link_to 'Услуги', services_path %></li>
          <li class="col"><%= link_to 'Прайс-лист', prices_url %></li>
          <li class="col"><%= link_to 'Контакты', contacts_path %></li>
        </ul>
      </div>
    </div>
  </header><!-- .header-->

<%= yield %>

  <footer class="footer">
    <div class="down">
      <div id="dwn" class="menu">
        <ul class="main">
          <li class="col"><a href="#">главная</a></li>
          <li class="col"><a href="#">услуги</a></li>
          <li class="col"><a href="#">прайс-лист</a></li>
          <li class="col"><a href="#">контакты</a></li>
        </ul>
      </div>
      <div class="adress">
        <p>ул. Васи - Победителя д.5</br>тел. 8 905 913 23 45</p>
      </div>
      <div class="wvar">
      </div>
    </div>
  </footer><!-- .footer -->

</div><!-- .wrapper -->


</body>
</html>

app/views/pages/contacts.html.erb
<main class="content">
  <div class="cont_ban"></div>
  <div class="cnt">
    <div class="line">
      <div class="inline">
        <h1>Свяжитесь с нами</h1>
      </div>
    </div>
    <div class="ml_tlphn">
      <div class="txt_ct phone">
        <h1>По телефону</h1>
        <p>8 909 904 12 45</br>
          8 909 904 12 45</p>
      </div>
      <div class="txt_ct mail">
        <h1>Через e-mail</h1>
        <p>forexample@gmail.com</br>forexample@gmail.com</p>
      </div>
    </div>
    <div class="line">
      <div class="inline cnt_inl">
        <h1>Или приезжайте</br>к нам</h1>
      </div>
    </div>
    <div class="adr_cnt"><p>
      Нижний Новгород, ул. Долгополова 50/40,  ТЦ "Порт Савин", офис 407
    </p></div>
  </div>

  <div class="adr_mp"><iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2212.7526497179274!2d43.946177!3d56.316841999999994!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4151d5c3391ed0cd%3A0x501239ca9dc70986!2z0YPQuy4g0JTQvtC70LPQvtC_0L7Qu9C-0LLQsCwgNTAsINCd0LjQttC90LjQuSDQndC-0LLQs9C-0YDQvtC0LCDQndC40LbQtdCz0L7RgNC-0LTRgdC60LDRjyDQvtCx0LvQsNGB0YLRjA!5e0!3m2!1sru!2sru!4v1402428927292" width="1366" height="384" frameborder="0" style="border:0"></iframe></div>

  <div class="cnt">
    <div class="line">
      <div class="inline">
        <h1>Наши партнёры</h1>
      </div>
    </div>
    <div class="circle prtn"><h1>1</h1></div>
    <div class="circle prtn"><h1>2</h1></div>
    <div class="circle prtn"><h1>3</h1></div>
    <div class="circle prtn"><h1>4</h1></div>
    <div class="circle prtn"><h1>5</h1></div>

  </div>
</main><!-- .content -->

app/views/pages/index.html.erb
<main class="content">
  <div class="banner"></div>
  <div class="cnt">
    <div class="line">
      <div class="inline inline_index">
        <h1>Бухгалтерские услуги в Нижнем Новгороде</h1>
      </div>
    </div>
    <div class="about">
      <p><span>Не секрет</span>, что все больше предприятий предпочитают отдавать бухгалтерию на аутсорсинг другим компаниям. Причины такого поведения очевидны. Снимая с себя часть расходов, вызванных необходимостью содержания бухгалтера в штате, Вы тем самым не только облегчаете платежное бремя, получая бухгалтерские услуги на самом высоком уровне, но и избавляете себя от возможных рисков, связанных с ошибками или неточностями в учете.

        Бухгалтерский аутсорсинг – отличное решение для тех предпринимателей, которые ценят качество услуг, и не хотят переплачивать. Мы не просто оказываем услуги, а становимся равноправными партнерами с нашими заказчиками. Трепетное отношение к каждому Клиенту, позволяет обеспечить индивидуальный подход, а также внести элемент творчества и креатива в процесс сотрудничества.

        <h3><b>ГРОССБУХ - Ваш надежный партнер в области аутсорсинга бухгалтерии!</b></h3> </p>
    </div><br/>
    <div class="line">
      <div class="inline">
        <h1>Наши услуги</h1>
      </div>
    </div>
    <div class="services_content">
    <% @services.each do |service| %>
    <div class="service">
      <div class="circle <%= ['one', 'two' , 'three', 'four'].to_a.shuffle.sample %>"></div>
      <div class="zag"><h1><%= link_to service_path(service) do %><%= service.title %><% end %></h1></div>
    </div>
    <% end %>
    </div>
    <div class="look_more">
    <%= button_to 'Смотреть все услуги!', services_path, class: 'btn btn-primary btn-lg', method: :get %>
    </div>
    <div class="brv">
      <div class="action">
        <div class="name_action">
          <p><span>Акция</span></br> скидка при заказе через сайт <span>40%</span>
          </p>
        </div>
      </div>
      <div class="sert">
        <h1>Сертификаты</h1>
      </div>
    </div>
    <div class="line">
      <div class="inline">
        <h1>Наши партнёры</h1>
      </div>
    </div>
    <div class="circle prtn"><h1>1</h1></div>
    <div class="circle prtn"><h1>2</h1></div>
    <div class="circle prtn"><h1>3</h1></div>
    <div class="circle prtn"><h1>4</h1></div>
    <div class="circle prtn"><h1>5</h1></div>
  </div>
</main><!-- .content -->

app/views/pages/order.html.erb
<h1>Pages#order</h1>
<p>Find me in app/views/pages/order.html.erb</p>

app/views/pages/prices.html.erb
<main class="content">
  <div class="price_ban"></div>
  <div class="cnt">
    <div class="line">
      <div class="inline">
        <h1>Наши цены</h1>
      </div>
    </div>
    <table class="table">
      <thead>
      <tr>
        <th>Наименование услуги</th>
        <th>Стоимость (руб./мес.)</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>Ведение бухгалтерского учета при различных системах налогообложения:</td>
        <td>----------------</td>
      </tr>
      <tr>
        <td> - ЕНВД, патент</td>
        <td>от 1 500 руб.</td>
      </tr>
      <tr>
        <td> - УСНО, объект налогообложения - доходы</td>
        <td>от 1 500 руб.</td>
      </tr>
      <tr>
        <td> - УСНО, объект налогообложения - доходы минус расходы</td>
        <td>от 3 000 руб.</td>
      </tr>
      <tr>
        <td> - традиционная система налогообложения</td>
        <td>от 5 000 руб.</td>
      </tr>
      <tr>
        <td>Сдача нулевой отчетности</td>
        <td>от 500 руб.</td>
      </tr>
      <tr>
        <td>Регистрация ООО «под ключ» (подготовка Устава, регистрация в ИФНС, фондах, статистике, изготовление печати, госпошлина, нотариус)</td>
        <td>10 000 руб.</td>
      </tr>
      <tr>
        <td>Регистрация ИП</td>
        <td>от 500 руб.</td>
      </tr>
      <tr>
        <td>Ведение кадрового делопроизводства</td>
        <td>от 1 000 руб.</td>
      </tr>
      <tr>
        <td>Консультирование по вопросам бухгалтерского учета и налогообложения (разовое/абонентское обслуживание)</td>
        <td>от 1 000 руб.</td>
      </tr>
      <tr>
        <td>Восстановление бухгалтерского учета</td>
        <td>от 7 000 руб.</td>
      </tr>
      <tr>
        <td>Составление ликвидационного баланса</td>
        <td>от 10 000 руб.</td>
      </tr>
      <tr>
        <td>Разработка и составление учетной политики</td>
        <td>от 3 000 руб.</td>
      </tr>
      <tr>
        <td>Подготовка финансовой части бизнес-планов</td>
        <td>от 15 000 руб.</td>
      </tr>
      <tr>
        <td>Анализ финансово-хозяйственной деятельности</td>
        <td>от 15 000 руб.</td>
      </tr>
      <tr>
        <td>Экспертиза бухгалтерских документов в рамках уголовных дел в сфере экономической деятельности</td>
        <td>от 15 000 руб.</td>
      </tr>
      </tbody>
    </table>
    <button type="button" class="btn btn-primary btn-lg btn-block">оставить заявку</button>
    <div class="line">
      <div class="inline">
        <h1>Наши партнёры</h1>
      </div>
    </div>
    <div class="circle prtn"><h1>1</h1></div>
    <div class="circle prtn"><h1>2</h1></div>
    <div class="circle prtn"><h1>3</h1></div>
    <div class="circle prtn"><h1>4</h1></div>
    <div class="circle prtn"><h1>5</h1></div>

  </div>
</main><!-- .content -->

app/views/pages/services.html.erb
<main class="content">
  <div class="pob_ban"></div>
  <div class="cnt">
    <div class="line">
      <div class="inline">
        <h1>услуга 1</h1>
      </div>
    </div>
    <div class="slogan">
      <div class="circle one slg_crcl"></div>
      <h1>Услуга 1 облегчит ваши проблемы!</h1>
    </div>
    <div class="cntr_cntn"><div class="news_srv">
      <div class="pct_srv"><img src="/images/new.jpg"></div>
      <div class="zgv_srv">
        <h1>Услуга 1</h1>
      </div>
      <div class="txt_srv"><p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.
      </p>
      </div>
      <button type="button" class="btn btn-primary btn-lg btn-block">оставить заявку</button>
    </div>
      <div class="nav"></div>
    </div>
    <div class="line">
      <div class="inline">
        <h1>наши партнёры</h1>
      </div>
    </div>
    <div class="circle prtn"><h1>1</h1></div>
    <div class="circle prtn"><h1>2</h1></div>
    <div class="circle prtn"><h1>3</h1></div>
    <div class="circle prtn"><h1>4</h1></div>
    <div class="circle prtn"><h1>5</h1></div>

  </div>
</main><!-- .content -->

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control', rows: 10 %>
  </div>
    <div class="field">
      <%= f.label :image_url %><br>
      <%= f.text_field :image_url, class: 'form-control' %>
    </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-default' %>
  </div>
</div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<main class="content">
  <div class="pob_ban"></div>
  <% @services.each do |service| %>
  <div class="cnt">
    <div class="line">
      <div class="inline inline_index">
        <%= link_to service_path(service) do %>
            <h1><%= service.title %></h1>
        <% end %>
      </div>
    </div>
    <div class="cntr_cntn"><div class="">
      <div class="pct_srv"><%= image_tag service.image_url %></div>
      <div class="txt_srv"><p><%= sanitize(service.span_this_please.truncate(1400)) %></p>
      </div>
      <div class="service_price"><%= service.price %></div>
      <%= link_to 'Поправить что-то здесь', edit_service_path(service) %>
      <%= link_to 'Удалить эту услугу', service_path(service), method: :delete %>
      <%= button_to 'Читать далее', service_path(service), class: 'btn btn-primary btn-lg btn-block', method: :get %>
    </div>
    </div>
  </div>
  <% end %>
  <%= will_paginate @services %>
</main><!-- .content -->

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<main class="content">
  <div class="pob_ban"></div>
  <div class="cnt">
    <div class="line">
      <div class="inline inline_index">
        <h1><%= @service.title %></h1>
      </div>
    </div>
    <div class="slogan">
      <div class="circle <%= ['one', 'two' , 'three', 'four'].to_a.shuffle.sample %> slg_crcl"></div>
      <h1>Услуга 1 облегчит ваши проблемы!</h1>
    </div>
    <div class="cntr_cntn"><div class="news_srv">
      <div class="pct_srv"><%= image_tag @service.image_url %></div>
      <div class="txt_srv"><p><%= sanitize(@service.span_this_please) %></p>
      </div>
      <div class="service_price"><%= @service.price %></div>
      <%= link_to 'Поправить что-то здесь', edit_service_path %>
      <%= link_to 'Удалить эту услугу', service_path, method: :delete %>
      <button type="button" class="btn btn-primary btn-lg btn-block">оставить заявку</button>
    </div>
      <div class="nav"></div>
    </div>
    <div class="line">
      <div class="inline">
        <h1>наши партнёры</h1>
      </div>
    </div>
    <div class="circle prtn"><h1>1</h1></div>
    <div class="circle prtn"><h1>2</h1></div>
    <div class="circle prtn"><h1>3</h1></div>
    <div class="circle prtn"><h1>4</h1></div>
    <div class="circle prtn"><h1>5</h1></div>

  </div>
</main><!-- .content -->